export { default as Home } from './Home'
export { default as Contact } from './Contact'
export { default as About } from './About'
export { default as Error } from './Error'
export { default as SignUp } from './SignUp'
export { default as SignIn } from './SignIn'