export { default as Header } from './Header'
export { default as Navbar } from './Navbar'
export { default as Footer } from './Footer'
export { default as Hero } from './Hero'
export { default as Categories } from './Categories'
export { default as BestProducts } from './BestProducts'
export { default as OurProducts } from './OurProducts'
export { default as Features } from './NewArrial'